categorias:
    path:     /
    defaults: { _controller: "uniMarcaBundle:categorias:index" }

categorias_show:
    path:     /{id}/show
    defaults: { _controller: "uniMarcaBundle:categorias:show" }
    
categorias_conSeguridad:
    resource: "@uniMarcaBundle/Resources/config/routing/conSeguridad/categoriasConSeguridad.yml"
    prefix:   /conSeguridad